module Icons.HerbGathering exposing (icon)

{-| HerbGathering icon

This file is AUTO-GENERATED by scripts/generate-custom-icons.js
DO NOT EDIT MANUALLY

Source: src/icons/svgs/herb-gathering.svg
Optimization: 394 rects → 85 merged → 1 path

-}

import Html.Attributes exposing (attribute)
import IdleGame.Views.Icon exposing (Icon(..), defaultParams)
import Svg
import Svg.Attributes


{-| The icon with currentColor support for theme-aware coloring
-}
icon : Icon
icon =
    let
        svgContent =
            Svg.svg
                [ Svg.Attributes.viewBox "0 0 32 32"
                , Svg.Attributes.width "100%"
                , Svg.Attributes.height "100%"
                , attribute "xmlns" "http://www.w3.org/2000/svg"
                , attribute "shape-rendering" "crispEdges" ]
                [ Svg.path
                    [ Svg.Attributes.d "M18 0h3v1h-3ZM30 0h2v1h-2ZM17 1h5v1h-5ZM30 1h2v1h-2ZM16 2h7v1h-7ZM29 2h3v1h-3ZM15 3h8v1h-8ZM28 3h4v1h-4ZM15 4h8v1h-8ZM27 4h5v1h-5ZM6 5h2v1h-2ZM15 5h8v1h-8ZM26 5h6v1h-6ZM6 6h3v1h-3ZM16 6h6v1h-6ZM26 6h5v1h-5ZM5 7h4v1h-4ZM17 7h4v1h-4ZM25 7h5v1h-5ZM5 8h5v1h-5ZM19 8h2v1h-2ZM24 8h5v1h-5ZM4 9h7v1h-7ZM19 9h2v1h-2ZM23 9h5v1h-5ZM4 10h8v1h-8ZM19 10h2v1h-2ZM22 10h5v1h-5ZM4 11h8v1h-8ZM19 11h8v1h-8ZM4 12h8v1h-8ZM19 12h7v1h-7ZM5 13h7v1h-7ZM19 13h4v1h-4ZM24 13h2v1h-2ZM5 14h7v1h-7ZM18 14h4v1h-4ZM23 14h3v1h-3ZM6 15h5v1h-5ZM17 15h4v1h-4ZM23 15h3v1h-3ZM7 16h3v1h-3ZM16 16h4v1h-4ZM24 16h2v1h-2ZM7 17h3v1h-3ZM15 17h4v1h-4ZM24 17h3v1h-3ZM8 18h2v1h-2ZM14 18h4v1h-4ZM25 18h3v1h-3ZM8 19h2v1h-2ZM13 19h5v1h-5ZM25 19h4v1h-4ZM8 20h2v1h-2ZM12 20h6v1h-6ZM24 20h6v1h-6ZM8 21h2v1h-2ZM11 21h4v1h-4ZM16 21h3v1h-3ZM24 21h7v1h-7ZM8 22h6v1h-6ZM15 22h4v1h-4ZM24 22h7v1h-7ZM8 23h5v1h-5ZM14 23h6v1h-6ZM24 23h8v1h-8ZM8 24h4v1h-4ZM14 24h7v1h-7ZM25 24h7v1h-7ZM7 25h3v1h-3ZM14 25h7v1h-7ZM26 25h6v1h-6ZM6 26h3v1h-3ZM14 26h7v1h-7ZM27 26h4v1h-4ZM4 27h4v1h-4ZM14 27h7v1h-7ZM29 27h2v1h-2ZM3 28h4v1h-4ZM15 28h6v1h-6ZM2 29h4v1h-4ZM16 29h4v1h-4ZM1 30h4v1h-4ZM17 30h2v1h-2ZM1 31h3v1h-3Z"
                    , Svg.Attributes.fill "currentColor"
                    ]
                    []
                ]
    in
    IconSvg svgContent defaultParams
