module Icons.WildMagic1 exposing (icon)

{-| WildMagic1 icon

This file is AUTO-GENERATED by scripts/generate-custom-icons.js
DO NOT EDIT MANUALLY

Source: src/icons/svgs/wild-magic-1.svg
Optimization: 353 rects → 70 merged → 1 path

-}

import Html.Attributes exposing (attribute)
import IdleGame.Views.Icon exposing (Icon(..), defaultParams)
import Svg
import Svg.Attributes


{-| The icon with currentColor support for theme-aware coloring
-}
icon : Icon
icon =
    let
        svgContent =
            Svg.svg
                [ Svg.Attributes.viewBox "0 0 32 32"
                , Svg.Attributes.width "100%"
                , Svg.Attributes.height "100%"
                , attribute "xmlns" "http://www.w3.org/2000/svg"
                , attribute "shape-rendering" "crispEdges"
                ]
                [ Svg.path
                    [ Svg.Attributes.d "M14 1h1v1h-1ZM9 2h1v1h-1ZM14 2h2v1h-2ZM8 3h2v1h-2ZM15 3h2v1h-2ZM7 4h2v1h-2ZM15 4h2v1h-2ZM7 5h3v1h-3ZM12 5h1v1h-1ZM15 5h2v1h-2ZM8 6h8v1h-8ZM9 7h6v1h-6ZM23 7h6v1h-6ZM10 8h6v1h-6ZM21 8h9v1h-9ZM11 9h5v1h-5ZM20 9h11v1h-11ZM2 10h4v1h-4ZM11 10h5v1h-5ZM19 10h12v1h-12ZM1 11h8v1h-8ZM11 11h5v1h-5ZM18 11h12v1h-12ZM1 12h9v1h-9ZM11 12h5v1h-5ZM17 12h12v1h-12ZM1 13h10v1h-10ZM12 13h16v1h-16ZM1 14h27v1h-27ZM2 15h23v1h-23ZM27 15h2v1h-2ZM3 16h9v1h-9ZM13 16h10v1h-10ZM27 16h2v1h-2ZM4 17h7v1h-7ZM13 17h6v1h-6ZM28 17h2v1h-2ZM8 18h1v1h-1ZM14 18h3v1h-3ZM18 18h2v1h-2ZM28 18h2v1h-2ZM7 19h2v1h-2ZM14 19h4v1h-4ZM19 19h2v1h-2ZM28 19h2v1h-2ZM7 20h2v1h-2ZM13 20h5v1h-5ZM20 20h3v1h-3ZM27 20h2v1h-2ZM7 21h2v1h-2ZM13 21h5v1h-5ZM21 21h7v1h-7ZM6 22h2v1h-2ZM13 22h2v1h-2ZM16 22h2v1h-2ZM22 22h5v1h-5ZM6 23h2v1h-2ZM13 23h2v1h-2ZM16 23h3v1h-3ZM7 24h2v1h-2ZM12 24h2v1h-2ZM17 24h2v1h-2ZM7 25h6v1h-6ZM17 25h3v1h-3ZM8 26h4v1h-4ZM18 26h3v1h-3ZM18 27h3v1h-3ZM18 28h4v1h-4ZM19 29h4v1h-4ZM20 30h3v1h-3Z"
                    , Svg.Attributes.fill "currentColor"
                    ]
                    []
                ]
    in
    IconSvg svgContent defaultParams
