module IdleGame.Views.CustomIcons exposing (..)

{-| Custom SVG icons generated from public/skills/

This file is AUTO-GENERATED by scripts/generate-custom-icons.js
DO NOT EDIT MANUALLY

-}

import Html exposing (Html)
import Html.Attributes exposing (attribute)
import IdleGame.Views.Icon exposing (Icon(..), Params, defaultParams)
import Svg
import Svg.Attributes



{-| wildMagic1 icon -}
wildMagic1 : Icon
wildMagic1 =
    let
        svgContent =
            Svg.svg
                [ Svg.Attributes.viewBox "0 0 32 32"
                , attribute "fill" "currentColor"
                , attribute "stroke" "currentColor"
                , attribute "xmlns" "http://www.w3.org/2000/svg"
                ]
                [ Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "2"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "3"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "3"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "4"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "4"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "5"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "5"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "5"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "6"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "6"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "6"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "6"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "6"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "10"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "7"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "29"
                    , Svg.Attributes.y "8"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "29"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "30"
                    , Svg.Attributes.y "9"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "2"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "3"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "29"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "30"
                    , Svg.Attributes.y "10"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "1"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "2"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "3"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "29"
                    , Svg.Attributes.y "11"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "1"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "2"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "3"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "12"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "1"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "2"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "3"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "10"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "13"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "1"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "2"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "3"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "10"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "14"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "2"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "3"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "10"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "15"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "3"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "10"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "16"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "4"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "5"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "10"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "17"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "18"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "18"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "18"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "18"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "18"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "18"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "19"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "19"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "19"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "19"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "19"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "19"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "28"
                    , Svg.Attributes.y "19"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "14"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "21"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "22"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "27"
                    , Svg.Attributes.y "20"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "15"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "23"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "24"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "25"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "26"
                    , Svg.Attributes.y "21"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "6"
                    , Svg.Attributes.y "22"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "22"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "22"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "22"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "7"
                    , Svg.Attributes.y "23"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "13"
                    , Svg.Attributes.y "23"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "16"
                    , Svg.Attributes.y "23"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "23"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "23"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "8"
                    , Svg.Attributes.y "24"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "12"
                    , Svg.Attributes.y "24"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "24"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "24"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "9"
                    , Svg.Attributes.y "25"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "10"
                    , Svg.Attributes.y "25"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "11"
                    , Svg.Attributes.y "25"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "17"
                    , Svg.Attributes.y "25"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "25"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "25"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "26"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "26"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "27"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "27"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "18"
                    , Svg.Attributes.y "28"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "28"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "20"
                    , Svg.Attributes.y "28"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                , Svg.rect
                    [ Svg.Attributes.x "19"
                    , Svg.Attributes.y "29"
                    , Svg.Attributes.width "1"
                    , Svg.Attributes.height "1"
                    , attribute "fill" "currentColor" ]
                    []
                ]
    in
    IconSvg svgContent defaultParams

